/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "fa.v:1.1-3.10" *)
module fa(a, b, c, co, sum);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "fa.v:1.18-1.19" *)
  wire _3_;
  (* src = "fa.v:1.28-1.29" *)
  wire _4_;
  (* src = "fa.v:1.38-1.39" *)
  wire _5_;
  (* src = "fa.v:1.48-1.50" *)
  wire _6_;
  (* src = "fa.v:1.60-1.63" *)
  wire _7_;
  (* src = "fa.v:1.18-1.19" *)
  input a;
  wire a;
  (* src = "fa.v:1.28-1.29" *)
  input b;
  wire b;
  (* src = "fa.v:1.38-1.39" *)
  input c;
  wire c;
  (* src = "fa.v:1.48-1.50" *)
  output co;
  wire co;
  (* src = "fa.v:1.60-1.63" *)
  output sum;
  wire sum;
  sky130_fd_sc_hd__maj3_1 _8_ (
    .A(_5_),
    .B(_3_),
    .C(_4_),
    .X(_6_)
  );
  sky130_fd_sc_hd__xor3_1 _9_ (
    .A(_5_),
    .B(_3_),
    .C(_4_),
    .X(_7_)
  );
  assign _5_ = c;
  assign _3_ = a;
  assign _4_ = b;
  assign co = _6_;
  assign sum = _7_;
endmodule

(* top =  1  *)
(* src = "rca.v:1.1-17.10" *)
module rca(num1, num2, sum);
  (* src = "rca.v:3.11-3.17" *)
  wire [7:0] int_co;
  (* src = "rca.v:2.12-2.19" *)
  wire [7:0] int_sum;
  (* src = "rca.v:1.25-1.29" *)
  input [7:0] num1;
  wire [7:0] num1;
  (* src = "rca.v:1.44-1.48" *)
  input [7:0] num2;
  wire [7:0] num2;
  (* src = "rca.v:1.64-1.67" *)
  output [8:0] sum;
  wire [8:0] sum;
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:8.6-8.86" *)
  fa \genblk1[1].u_fa_1  (
    .a(num1[1]),
    .b(num2[1]),
    .c(int_co[0]),
    .co(int_co[1]),
    .sum(int_sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:8.6-8.86" *)
  fa \genblk1[2].u_fa_1  (
    .a(num1[2]),
    .b(num2[2]),
    .c(int_co[1]),
    .co(int_co[2]),
    .sum(int_sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:8.6-8.86" *)
  fa \genblk1[3].u_fa_1  (
    .a(num1[3]),
    .b(num2[3]),
    .c(int_co[2]),
    .co(int_co[3]),
    .sum(int_sum[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:8.6-8.86" *)
  fa \genblk1[4].u_fa_1  (
    .a(num1[4]),
    .b(num2[4]),
    .c(int_co[3]),
    .co(int_co[4]),
    .sum(int_sum[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:8.6-8.86" *)
  fa \genblk1[5].u_fa_1  (
    .a(num1[5]),
    .b(num2[5]),
    .c(int_co[4]),
    .co(int_co[5]),
    .sum(int_sum[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:8.6-8.86" *)
  fa \genblk1[6].u_fa_1  (
    .a(num1[6]),
    .b(num2[6]),
    .c(int_co[5]),
    .co(int_co[6]),
    .sum(int_sum[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:8.6-8.86" *)
  fa \genblk1[7].u_fa_1  (
    .a(num1[7]),
    .b(num2[7]),
    .c(int_co[6]),
    .co(int_co[7]),
    .sum(int_sum[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:12.4-12.77" *)
  fa u_fa_0 (
    .a(num1[0]),
    .b(num2[0]),
    .c(1'h0),
    .co(int_co[0]),
    .sum(int_sum[0])
  );
  assign sum = { int_co[7], int_sum };
endmodule
