/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "good_mux.v:2.1-12.10" *)
module good_mux(i0, i1, sel, y);
  (* src = "good_mux.v:3.11-3.13" *)
  wire _0_;
  (* src = "good_mux.v:4.11-4.13" *)
  wire _1_;
  (* src = "good_mux.v:5.11-5.14" *)
  wire _2_;
  (* src = "good_mux.v:6.16-6.17" *)
  wire _3_;
  (* src = "good_mux.v:3.11-3.13" *)
  input i0;
  wire i0;
  (* src = "good_mux.v:4.11-4.13" *)
  input i1;
  wire i1;
  (* src = "good_mux.v:5.11-5.14" *)
  input sel;
  wire sel;
  (* src = "good_mux.v:6.16-6.17" *)
  output y;
  wire y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_2_),
    .X(_3_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _2_ = sel;
  assign y = _3_;
endmodule
