/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "bad_mux.v:3.1-11.10" *)
module bad_mux(i0, i1, sel, y);
  (* src = "bad_mux.v:3.23-3.25" *)
  wire _0_;
  (* src = "bad_mux.v:3.34-3.36" *)
  wire _1_;
  (* src = "bad_mux.v:3.45-3.48" *)
  wire _2_;
  (* src = "bad_mux.v:3.62-3.63" *)
  wire _3_;
  (* src = "bad_mux.v:3.23-3.25" *)
  input i0;
  wire i0;
  (* src = "bad_mux.v:3.34-3.36" *)
  input i1;
  wire i1;
  (* src = "bad_mux.v:3.45-3.48" *)
  input sel;
  wire sel;
  (* src = "bad_mux.v:3.62-3.63" *)
  output y;
  wire y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_2_),
    .X(_3_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _2_ = sel;
  assign y = _3_;
endmodule
