/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "ternary_operator_mux.v:1.1-3.11" *)
module ternary_operator_mux(i0, i1, sel, y);
  (* src = "ternary_operator_mux.v:1.36-1.38" *)
  wire _0_;
  (* src = "ternary_operator_mux.v:1.47-1.49" *)
  wire _1_;
  (* src = "ternary_operator_mux.v:1.58-1.61" *)
  wire _2_;
  (* src = "ternary_operator_mux.v:1.71-1.72" *)
  wire _3_;
  (* src = "ternary_operator_mux.v:1.36-1.38" *)
  input i0;
  wire i0;
  (* src = "ternary_operator_mux.v:1.47-1.49" *)
  input i1;
  wire i1;
  (* src = "ternary_operator_mux.v:1.58-1.61" *)
  input sel;
  wire sel;
  (* src = "ternary_operator_mux.v:1.71-1.72" *)
  output y;
  wire y;
  sky130_fd_sc_hd__mux2_1 _4_ (
    .A0(_0_),
    .A1(_1_),
    .S(_2_),
    .X(_3_)
  );
  assign _0_ = i0;
  assign _1_ = i1;
  assign _2_ = sel;
  assign y = _3_;
endmodule
